### PR TITLE
Simplify repository contents

### PR DESCRIPTION
**Pull request by yuvipanda**
- Get jupyter-remote-desktop from pip, rather than ship it
  as part of the repo
- jupyter-remote-desktop ships with a version of tigervnc,
  no need to install it separately
- The Dockerfile was overriding apt.txt, and is no longer needed
  anyway. The default repo2docker setup works
- We don't explicitly turn off the screensaver, which might be
  problem now. Not sure though, maybe it's ok? :)
- Adds a desktop qgis launcher icon
  
image

### CODE REVIEW

**Comment by yuvipanda** [comment]
I also made a template repo that can be used to generate these kinda repos in the future https://github.com/yuvipanda/binder-desktop-app-template

**Comment by yuvipanda** [comment]
You can try this out on https://mybinder.org/v2/gh/yuvipanda/jupyter-desktop-server/qgis?urlpath=desktop

**Comment by giswqs** [comment]
Sorry for the delay. This PR slipped through me.

**Comment by yuvipanda** [comment]
yay, thanks for the merge @giswqs

**Pull request merged**
